# Generated by Django 5.2.7 on 2025-10-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_encypted', models.CharField()),
                ('algorithm', models.CharField(choices=[('caesar', 'Caesar'), ('affine', 'Affine'), ('playfair', 'playfair'), ('hill', 'hill')], max_length=20)),
                ('key_data', models.JSONField()),
            ],
        ),
    ]
